services:
- docker
install: make docker-login build
stages:
- name: echo
- name: publish
  if: branch = main AND type != pull_request
jobs:
  include:
  - stage: echo
    script: echo
  - stage: publish
    name: Publish production image
    script:
    - make publish
env:
  global:
  - secure: wNlMsf8g8/z7S286D75lpElQYXV+FSV+EYtqZMdoThfQ28b4p1+Zf15VUjEdToISsiwbCaHRJMBiWcrK9tf5BrUalfQAWvjusLxVLanvYVmnEMjJVGF5R8ZELJ21BB979eV1Ojfgine4h2gfUM10RejCprqYXUhhlH4DWY2n2y4zda+bTPs3sMSZrN+U3KIm2Dv/uHforo38U4VGbhG8cE39DB1EG7Bf4qRfNsz8i4ZDgxpffvZkfRbOPr86e1CLtXTJWKVAlpbGqYZ6rSKuF3hiwUG0dlYxlehXfEMarYvDRxi1fMFhX/IHBWUX4I4ewHBNE0dMt3D2o1IvsLJBRLOkvLOtWwxd/T/TM7j7RcuQogyxZ4fHdaVa80DcQpDL3EoShZ5yNgd3AcQwg7DRCJ1RRDn7be1eTxGBtV02Lb9Yx2Sx7MA7JXFIE/qCL/A2jtcRvd1FyrfsO3q9f40BGSumLYGkumwGkr2VEgpNSic90FiHdZIcvqUypK0yDSskx2TTimRo61uHHkAgyClsIEIADRig47QAsC+hCxYCTm6JmM/KCpbDfKg9uV4ok4pqdfdFaqmry0RE5GkP/gTMMwv9v+FWkaipl66Gdi+loV9mHrmMdnsDpvzK8BQJEqcBoCpOIofdpemBU4yS3bUBXPkqHm+sAMP3tciq3dWOSq8=
  - secure: 5C1bNSyUKn0Y4BfVXn7uj5dHm7mkPXg/WYKfmMqjHpGoJShZg+ZdZReX6mquZIO79OXlf2SGiOsmxUBF6/QIdPT+poa65CeHRRa04ijhQoV4FeJjgCPyBOg6d5iabxO2K1GMZ43FgZ9JAI04sUs7kd7e+VT3/efsCzKj+8yzTBUYgr5B6Ky9XM1SMMVGmetgwDEaYVwcMLVvJ2yrcCGODywcL3ujuCQdcHwiLh3mAL7d8sMXrI0+Zzc0SUAijKZKlClOpr75746CZ8L7NM8DUBiNCPtLxuTflVPPEXKDm8FuWN5kz3azW1UwIicmAQ9M5b4/5IUDkDLTy07Spp75pV+UXqAd0/IC2vLVQXqrP28jAbuy4WSpu5ttD5dHN0ArYh+erepiJQjD51q5wx7lYpDr64LLv/lcCMtEoP7mHSM+VQOblWyG9j+yMNZC7i7Yef6iB6o7fQ82Ime+YYspDZsBydKtrgP+eA1myLspgM5GlZ1Sn/c5kAQI8bQfkgJBKKP5Z4aUzFOPFLpniRKoNwtsZDawgES8m/scKOeeFvhinZmzr7AXF8wAgPcMUHFy3fEOPZsW/ioeYeisqBeEcRawBt5WUbMsW7YhvzeykSdwlDomRg1I3DVvuqmLF5GNPKCwG3zkX2eaua+FVREr9IWMCQp6UFvLAxKK+59irpI=
