ARG REPOSITORY=docker.osdc.io
ARG BUILDER_TAG=3.1.0

### Download tarball to scratch layer
FROM scratch AS src
ARG VERSION
ADD https://github.com/NCI-GDC/bwa/archive/gdc_a.tar.gz /gdc_a.tar.gz

FROM ${REPOSITORY}/ncigdc/amzn2023-builder:${BUILDER_TAG} AS builder

ARG VERSION

### Mount tarball from scratch layer and untar into builder layer
RUN --mount=from=src,target=/src <<EOF
mkdir -p /gdc_a
tar -oxzf /src/gdc_a.tar.gz -C /gdc_a/.
EOF

# Example add package step
RUN dnf install -y \
       bzip2 \
       gcc \
       libbz2-dev \
       liblzma-dev \
       libncurses5-dev \
       make \
       wget \
       zlib1g-dev

### Multi-stage build:
FROM ${REPOSITORY}/ncigdc/samtools:1.9-0bce9a0
COPY --from=builder /usr/local /usr/local

### Run install steps
WORKDIR /gdc_a/bwa-gdc_a

RUN <<EOF
make
mv bwa /usr/local/bin/
EOF

ENTRYPOINT ["/usr/bin/dumb-init", "--"]
